# Input
samplesheet:  "/mctp/paroliaAnalysis/kevhu/chipseq/samplesheet.csv"
fastq_dir:    "/mctp/paroliaAnalysis/kevhu/chipseq/fastq"

# Output
outdir:       "/mctp/paroliaAnalysis/kevhu/chipseq/results"

# Reference files (hg38) — all in eleanoyo's REF folder, mounted as /data2 in the chipimage Docker
ref_dir:      "/mctp/share/users/eleanoyo/REF/hg38_path5_USE"
chrom_sizes:  "/mctp/share/users/eleanoyo/REF/hg38_path5_USE/hg38.genome"
blacklist_bed: "/mctp/share/users/eleanoyo/REF/hg38_path5_USE/FixBlacklist_ENCFF356LFX.bed"

# IgG control BAM for MACS2 peak calling (update per experiment)
igg_bam:      "/mctp/share/users/eleanoyo/REF/hg38_path5_USE/SI_40572_VCaP_DMSO_IgG_aligned_PCRDupes.bam"

# Trimmomatic adapter file
trimmomatic_adapters: "/mctp/share/users/eleanoyo/Software/trimmomatic/adapters/TruSeq3-PE-2.fa"
